# Generated by Django 4.2.2 on 2023-06-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_start', models.DateTimeField(db_column='post start', default=datetime.datetime(2023, 6, 17, 11, 23, 1, 915473, tzinfo=datetime.timezone.utc), help_text='Specify the start date and time of the mailing.', verbose_name='Post start')),
                ('content', models.CharField(db_column='content', help_text='Enter the text you want to send to customers.', max_length=255, verbose_name='Content')),
                ('post_end', models.DateTimeField(db_column='post end', default=datetime.datetime(2023, 6, 17, 11, 23, 1, 915473, tzinfo=datetime.timezone.utc), help_text='Specify the date and time when the mailing ends.', verbose_name='Post end')),
                ('filter_operator_code', models.ManyToManyField(db_column='operator code', help_text='Select the operator code for customers.', to='client.codeoperator', verbose_name='Operator code')),
                ('filter_tag', models.ManyToManyField(db_column='tag', help_text='Select customer Tag.', to='client.tag', verbose_name='Tag')),
            ],
        ),
    ]
